### ISSUE TITLE
Allow cosocket recv and send to work from different cothreads

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/cothread#1]
At present, if you do a recv() in one cothread, then do a send() in another thread and while servicing the send there is a message received, the cothread blocking on recv() will never wake up.

The easy fix is to always poll on POLLIN and POLLOUT for both send and recv.

**Comment by Araneidae** [comment]
Tom, can you update this please -- I think this isn't quite valid as it stands, as we've discussed.

**Comment by thomascobb** [comment]
Turns out this was an issue with zmq rather than cosocket.
