### ISSUE TITLE
numpy dependency

### ISSUE THREAD

**Issue by femanov** [dls-controls/cothread#2]
it depend on numpy 1.7.2 and "pip install ..." will change  numpy > 1.7.2 to numpy 1.7.2

but i think it will work with numpy > 1.7.2

**Comment by Araneidae** [comment]
Certainly cothread is not tied to any particular version of numpy, and I can't see anything in the install code that sets the version.  Can you expand on this report at all, please, I don't think I fully understand it.

**Comment by femanov** [comment]
last time I used command "pip install cothread --upgrade", it's uninstalled
numpy 1.10, and installed 1.7.2 for dependency. Any Ideas why?

**Comment by Araneidae** [comment]
Ick.  I'll investigate!

**Comment by thomascobb** [comment]
I've tried to recreate this but I can't. Could you provide some more details about the machine, OS, version of python, and commandline output that produced this situation please?

The code doesn't refer to numpy 1.7.2 anywhere that I can see, so I'm baffled at how it would be doing this...

**Comment by femanov** [comment]
Hi, I've seen it on Scientific Linux 6, python 2.6.6, pip 1.4.1, I
reinstalled numpy 1.10, and can't  reproduce it any more, possibly it's
some problem from my side.
