### ISSUE TITLE
trouble installing cothread

### ISSUE THREAD

**Issue by crispd** [dls-controls/cothread#25]
I've tried all the install methods I could find, yet it doesn't appear to be working. Any help would be much appreciated.

I'm running these in the anaconda prompt, as administrator, on a windows machine, with an environment using python 3.10.2.
I can get it installed in WSL, but I'd really like to have it in my anaconda environment if possible. Again, thank you for any and all help.

I'm also wondering what the steps should be if I wanted to try manually installing it from source (git cloning somewhere, and either running some install script or manually adding modules to my path)? I've just never imported python modules from source to an anaconda environment before, so some guidance would be appreciated. Thank you!

----------------------------------------------------------------------------------------------------------------------------------------
*see below for images describing my attempts*

![image](https://user-images.githubusercontent.com/7905813/156420026-9b70dd96-95c9-47a4-88bf-1a8b23c1af11.png)
----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/7905813/156420117-fee79be0-c642-4b5d-8089-0aee7e1b7db0.png)
----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/7905813/156420378-f9992218-f035-4d84-9289-9bb39fc169f6.png)
----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/7905813/156420586-0724157b-16b4-4880-b79d-141369249e2c.png)

**Comment by crispd** [comment]
I noticed if I cloned other packages manually, and ran `python setup.py install`, it does actually copy files over to the right environment location. So after successfully doing this operation with an unrelated package, I tried manually installing cothread from this github repo. However, I'm getting some error related to cl.exe in Microsoft Visual Studio?
```
building 'cothread._coroutine' extension
"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\envs\py310\include -IC:\ProgramData\Anaconda3\envs\py310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tccontext/_coroutine.c /Fobuild\temp.win-amd64-3.10\Release\context/_coroutine.obj -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wundef -Wcast-align -Wwrite-strings -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes
cl : Command line error D8021 : invalid numeric argument '/Wextra'
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```
I'm not sure why it's referring to Microsoft Visual Studio, but maybe that doesn't matter. It appears to me that the issue is with this /Wextra argument being invalid somehow. Is anyone here familiar with this error?

**Comment by crispd** [comment]
Appears /Wextra is a GCC compiler flag that helps warn you about specific compiler issues. However, I'm still not sure why the argument is invalid. Is there a specific version of GCC I need to install to make this work?

**Comment by Araneidae** [comment]
Hmm.

You're entering uncharted territory here.  Basically cothread doesn't work on Windows, and hasn't worked for probably a decade.  If you _do_ want to try running on Windows I last tried it with MinGW, which I seem to remember was GCC packaged up to run on Windows.

The reason `/Wextra` isn't working for you is that you're not actually using GCC to build it ... the reference to "Microsoft Visual Studio" _does_ matter, quite a bit here!

So, cothread isn't available on anaconda for Windows because cothread isn't released on Windows.  The reason cothread doesn't work on Windows is a subtle problem to do with implementing `select`, and you can find an entire essay on the topic in [cothread/poll_win32.py](https://github.com/dls-controls/cothread/blob/master/cothread/poll_win32.py) (from line 80).

On the other hand, you may be able to do what you want with [aioca](https://github.com/dls-controls/aioca).  Its interface is derived from `cothread`, but it uses `async` instead of cothreads.

**Comment by Araneidae** [comment]
I'm going to close this issue now, but do let me know if you need any more information.

**Comment by crispd** [comment]
Thank you so much for these details! aioca looks fine to me, I didn't know it existed. Another option I hadn't considered is running my VScode instance within my WSL environment, where it actually was possible to install cothread. Again, thanks so much for the information, I really appreciate it.
