### ISSUE TITLE
PyPI homepage link broken

### ISSUE THREAD

**Issue by smartsammler** [dls-controls/cothread#26]
The link shown on PyPI seems to be broken:
https://github.com/dls-controls/cothread/blob/5beaacfa40401119a5979b7557ddad5d92c980f8/setup.py#L74

If it is just a temporary issue with the host, please ignore this issue, otherwise it would make sense to point to the current location or maybe to this GitHub repository.

Unfortunately, I don't know what the link's destination was, so I can't provide a meaningful PR.

Thank you very much.

**Comment by Araneidae** [comment]
That's unfortunate.  Yes, this needs to be changed to point to github, looks like our outward facing web server got turned off...
