### ISSUE TITLE
work with QCoreApplication

### ISSUE THREAD

**Issue by femanov** [dls-controls/cothread#5]
Hello,
## Code like  this

QtCore.QCoreApplication(sys.argv)
app = cothread.iqt()
...
Some code
...
## cothread.WaitForQuit()

Unfortunatly will not not work, dew to input_hook.py, line 139:
    _qapp.lastWindowClosed.connect(cothread.Quit)

I suggest to change it to:
    _qapp.aboutToQuit.connect(cothread.Quit)

It will work the same for GUI apps while quitOnLastWindowClosed is True. If somebody set it to False, my suggesion looks even more correct.

Thank you.
Fedor.

PS. I know that I can make console app without Qt, but there are some strong reasons to use Qt.

**Comment by Araneidae** [comment]
Thank you for this, this sounds interesting, I will investigate.

**Comment by Araneidae** [comment]
@femanov , did you want to revisit this?  If there's a fix you'd like me to pull I'll take a look.

**Comment by femanov** [comment]
fix is already in it's place. See input_hook.py line 130:
_qapp = QtCore.QCoreApplication.instance()

--------------------
this works with QApplication as it inherited from QGuiApplication, which inherits QCoreApplication. (for Qt5). So it's closed.
